{*******************************************************}
{* 
{* uMatchAccuracy.pas
{* Delphi Implementation of the Class MatchAccuracy
{* Generated by Enterprise Architect
{* Created on:      09-févr.-2015 11:41:48
{* Original author: Brady Vidovic   OK
{*  
{*******************************************************}

unit uMatchAccuracy;

interface

type


    TMatchAccuracy=   (
    //ordered from best to worst
    ORIGINAL_AIR_DATE_AND_EXACT_TITLE,
    ORIGINAL_AIR_DATE_AND_FUZZY_TITLE,
    ORIGINAL_AIR_DATE_AND_CONTAINS_TITLE,
    EXACT_TITLE,
    ORIGINAL_AIR_DATE,
    FUZZY_TITLE,
    CONTAINS_TITLE
  );


    type TMatchAccuracyHelper = record helper for TMatchAccuracy
    public
      function ToString() : string;
      end;


implementation

  uses TypInfo;


{ TStringsHelper }


function TMatchAccuracyHelper.ToString: string;
begin
       Result := GetEnumName(TypeInfo(TMatchAccuracy), integer(Self)) ;
end;

end.