{ ******************************************************* }
{ *
  {* uMatch.pas
  {* Delphi Implementation of the Class Match
  {* Generated by Enterprise Architect
  {* Created on:      09-févr.-2015 11:44:54
  {* Original author: Labelleg
  {*
  {******************************************************* }

unit uMatch;

interface

uses uMatchAccuracy, uTVDBSeries, uTVDBEpisode, System.Generics.Collections;

type

  TMatch = class(TInterfacedObject, IComparable<TObject>)
  private
  protected
    function QueryInterface(const IID: TGUID; out Obj): HResult; stdcall;
    function _AddRef: Integer; stdcall;
    function _Release: Integer; stdcall;
  public
    accuracy: TMatchAccuracy;
    matchingEpisodes: TVDBEpisodeColl;
    series: TTVDBSeries;

    function CompareTo(Value: TObject): Integer;

    constructor Create(matchAccuracy: TMatchAccuracy; series: TTVDBSeries; matchingEpisodes: TVDBEpisodeColl);

    destructor Destroy; override;

  end;

  TMatchColl = class(TObjectList<TMatch>)
  public
    constructor Create();

    destructor Destroy; override;

  end;

implementation

uses
  System.SysUtils;

{ implementation of Match }

function TMatch.CompareTo(Value: TObject): Integer;
begin
  raise Exception.Create('Code no complété');
end;

constructor TMatch.Create(matchAccuracy: TMatchAccuracy; series: TTVDBSeries; matchingEpisodes: TVDBEpisodeColl);
begin
  inherited Create;
  Self.matchingEpisodes := matchingEpisodes;
  Self.accuracy := matchAccuracy;
  Self.series := series;

end;

destructor TMatch.Destroy;
begin

  inherited;
end;

function TMatch.QueryInterface(const IID: TGUID; out Obj): HResult;
begin
  QueryInterface := 0;
end;

function TMatch._AddRef: Integer;
begin
  _AddRef := 0;
end;

function TMatch._Release: Integer;
begin
  _Release := 0;
end;

{ TMatchColl }

constructor TMatchColl.Create;
begin
  inherited Create;

  OwnsObjects := true;
end;

destructor TMatchColl.Destroy;
begin

  inherited;
end;

end.
