{ ******************************************************* }
{ *
  {* uTVDBSeries.pas
  {* Delphi Implementation of the Class TVDBSeries
  {* Generated by Enterprise Architect
  {* Created on:      09-févr.-2015 11:43:46
  {* Original author: bvidovic    OK
  {*
  {******************************************************* }

unit uTVDBSeries;

interface

uses
  System.Generics.Collections;

type

  TTVDBSeries = class
  strict private
    FseriesId: String;
    FseriesName: String;
    FseriesYear: String;

  public
    // equality basaed on seriesId
    function equals(const o: TTVDBSeries): boolean;  reintroduce;
    property seriesId: String read FseriesId write FseriesId;
    property seriesName: String read FseriesName write FseriesName;
    property seriesYear: String read FseriesYear write FseriesYear;

    function hashCode: Integer;
    function toString: String;  reintroduce;

    constructor Create(const seriesId: String; const seriesName: String;const  seriesYear: String); overload;
    constructor Create(const seriesId: String); overload;

    destructor Destroy; override;
  end;

  TTVDBSeriesColl = Class(TObjectList<TTVDBSeries>)
  public
    constructor Create; overload;

    destructor Destroy; override;

  End;

implementation

uses
  System.SysUtils;

{ implementation of TVDBSeries }

constructor TTVDBSeries.Create(const seriesId, seriesName, seriesYear: String);
begin
  inherited Create;
  Self.FseriesId := seriesId;
  Self.FseriesName := seriesName;
  Self.FseriesYear := seriesYear;
end;

constructor TTVDBSeries.Create(const seriesId: String);
begin

  inherited Create;
  Self.FseriesId := seriesId;
end;

destructor TTVDBSeries.Destroy;
begin
  inherited Destroy;
end;

function TTVDBSeries.equals(const o: TTVDBSeries): boolean;
var
  otherSeries: TTVDBSeries;
begin

  otherSeries := o;

  if (Self.FseriesId = '') then
  begin
    Result := (otherSeries.seriesId = '');
  end
  else
  begin
    Result := SameText(Self.seriesId, otherSeries.seriesId);
  end;

end;

function TTVDBSeries.hashCode: Integer;
var
  hash: Integer;
begin
  hash := 3;
  hash := 97 * hash + Self.seriesId.GetHashCode; // Objects.hashCode(this.seriesId);
  Result := hash;
end;

function TTVDBSeries.toString: String;
begin
  Result := 'tvdbid: ' + seriesId + ', seriesName: ' + seriesName + ', seriesYear: ' + seriesYear;
end;

{ TTVDBSeriesColl }

constructor TTVDBSeriesColl.Create;
begin
  inherited Create;

  Self.OwnsObjects := true;
end;

destructor TTVDBSeriesColl.Destroy;
begin

  inherited;
end;

end.
