{ ******************************************************* }
{ *
  {* uTVDBEpisode.pas
  {* Delphi Implementation of the Class TVDBEpisode
  {* Generated by Enterprise Architect
  {* Created on:      09-févr.-2015 11:43:17
  {* Original author: Labelleg  OK
  {*
  {******************************************************* }

unit uTVDBEpisode;

interface

uses System.Generics.Collections;

type
  ITVDBEpisode = interface['{95CA74BA-EDD5-44B3-A3C6-6158DCD22E5B}']
    function toString: String;
//    procedure SetepisodeNumber(const Value: String);
//    procedure SetfirstAired(const Value: String);
//    procedure SethasImage(const Value: boolean);
//    procedure SetseasonNumber(const Value: String);
//    procedure Settitle(const Value: String);
    function GetepisodeNumber: String;
    function GetfirstAired: String;
    function GethasImage: boolean;
    function GetseasonNumber: String;
    function Gettitle: String;

  end;

  TTVDBEpisode = class(TInterfacedObject,ITVDBEpisode)
  strict private
    FepisodeNumber: String;
    FfirstAired: String;
    FhasImage: boolean;
    FseasonNumber: String;
    Ftitle: String;
  public
//    procedure SetepisodeNumber(const Value: String);
//    procedure SetfirstAired(const Value: String);
//    procedure SethasImage(const Value: boolean);
//    procedure SetseasonNumber(const Value: String);
//    procedure Settitle(const Value: String);
    function GetepisodeNumber: String;
    function GetfirstAired: String;
    function GethasImage: boolean;
    function GetseasonNumber: String;
    function Gettitle: String;


//    property episodeNumber: String read GetepisodeNumber write SetepisodeNumber;
//    property firstAired: String read GetfirstAired write SetfirstAired;
//    property hasImage: boolean read GethasImage write SethasImage;
//    property seasonNumber: String read GetseasonNumber write SetseasonNumber;
//    property title: String read Gettitle write Settitle;

    function toString: String;  reintroduce;
    constructor Create(tvdbTitle: String; tvdbFirstAired: String; tvdbSeasonNumber: String; tvdbEpisodeNumber: String;    hasTVDBImage: boolean); overload;

    destructor Destroy; override;
  end;

  TVDBEpisodeColl = class(TList<ITVDBEpisode>)
  public
    constructor Create; overload;
    destructor Destroy; override;

    function containsAll(coll: TVDBEpisodeColl): boolean;
    function IsEmpty: boolean;

    function toString: String; reintroduce;
  end;

implementation

{ implementation of TVDBEpisode }

constructor TTVDBEpisode.Create(tvdbTitle, tvdbFirstAired, tvdbSeasonNumber, tvdbEpisodeNumber: String;
  hasTVDBImage: boolean);
begin
  inherited Create;

  self.Ftitle := tvdbTitle;
  self.FfirstAired := tvdbFirstAired;
  self.FseasonNumber := tvdbSeasonNumber;
  self.FepisodeNumber := tvdbEpisodeNumber;
  self.FhasImage := hasTVDBImage;
end;

destructor TTVDBEpisode.Destroy;
begin
  inherited Destroy;
end;

function TTVDBEpisode.GetepisodeNumber: String;
begin
  Result := FepisodeNumber;
end;

function TTVDBEpisode.GetfirstAired: String;
begin
  Result := FfirstAired;
end;

function TTVDBEpisode.GethasImage: boolean;
begin
Result := FhasImage;
end;

function TTVDBEpisode.GetseasonNumber: String;
begin
    Result := FseasonNumber;
end;

function TTVDBEpisode.Gettitle: String;
begin
    Result := Ftitle
end;

//procedure TTVDBEpisode.SetepisodeNumber(const Value: String);
//begin
//  FepisodeNumber := Value;
//end;
//
//procedure TTVDBEpisode.SetfirstAired(const Value: String);
//begin
//  FfirstAired := Value;
//end;
//
//procedure TTVDBEpisode.SethasImage(const Value: boolean);
//begin
//  FhasImage := Value;
//end;
//
//procedure TTVDBEpisode.SetseasonNumber(const Value: String);
//begin
//  FseasonNumber := Value;
//end;
//
//procedure TTVDBEpisode.Settitle(const Value: String);
//begin
//  Ftitle := Value;
//end;

function TTVDBEpisode.toString: String;
begin
  Result := FseasonNumber + 'x' + FepisodeNumber + ' - ' + Ftitle + ' (' + FfirstAired + ')';
end;

{ TVDBEpisodeColl }

function TVDBEpisodeColl.containsAll(coll: TVDBEpisodeColl): boolean;
var
  unElement: ITVDBEpisode;
begin

  for unElement in coll do
  begin
    if not self.Contains(unElement) then
    begin
      Result := False;
      exit;
    end;

  end;
  Result := True;

end;

constructor TVDBEpisodeColl.Create;
begin
  inherited Create();
//  OwnsObjects := True;

end;

destructor TVDBEpisodeColl.Destroy;
begin

  inherited;
end;

function TVDBEpisodeColl.IsEmpty: boolean;
begin
  Result := (self.Count = 0);
end;

function TVDBEpisodeColl.toString: String;
var
  item: ITVDBEpisode;
begin

  Result := '';

  for item in self do
  begin
    Result := Result + '; ' + item.toString;
  end;

end;

end.
